#!/bin/bash

APPS=/usr/share/applications
ICONS=/usr/share/icons
SIZE=48

echo "Generating config file from $APPS ..." >&2

find $APPS -name "*.desktop" | while read DESKTOPFILE; do
   FDATA="$(cat $DESKTOPFILE)"
   NAME="$(echo "$FDATA" | grep -i "^Name=" | head -n 1 | cut -d "=" -f 2-)"
   EXEC="$(echo "$FDATA" | grep -i "^Exec=" | head -n 1 | cut -d "=" -f 2-)"
   ICONNAME="$(echo "$FDATA" | grep -i "^Icon=" | head -n 1 | cut -d "=" -f 2-)"
   USETERM="$(echo "$FDATA" | grep -i "^Terminal=" | head -n 1 | cut -d "=" -f 2-)"
   if [ "$USETERM" = "true" ]; then
      EXEC="$TERM -e ""$EXEC"
   fi

   if [ "$ICONNAME" != "" ]; then
      ICON="$(find "$ICONS" | grep $SIZE"x"$SIZE | grep $ICONNAME"[.]png" | head -n 1)"
      if [ "$ICON" != "" -a "$EXEC" != "" -a "$NAME" != "" ]; then
         echo "$NAME;$ICON;$EXEC"
      else
        ICON="$(find "$ICONS" | grep "scalable" | grep -E $ICONNAME"[.](png|svg)" | head -n 1)"
        if [ "$ICON" != "" -a "$EXEC" != "" -a "$NAME" != "" ]; then
           echo "$NAME;$ICON;$EXEC"
        fi
      fi
   fi
done | sort | uniq
