#!/bin/bash

globalappfolder=/usr/share/applications
localappfolder=$HOME/.local/share/applications
pixmaps=/usr/share/pixmaps
globaliconfolder=/usr/share/icons
localiconfolder=$HOME/.local/share/icons
homeiconfolder=$HOME/.icons
iconsize=64
icontheme=$(cat $HOME/.gtkrc-2.0 | sed -n 's/^gtk-icon-theme-name="\([^"]*\)"$/\1/p')
cansvg=$(type convert >/dev/null 2>&1 && echo "true" || echo "false")

iconname="firefox"
icontheme="Adwaita"

if ! [ -z "$icontheme" ]; then
	iconpath="/usr/share/icons/$icontheme"
	inherits=$(cat $(find $iconpath -name "index.theme") | sed -n "s|^Inherits=\(.*\)$|\1|p" | sed "s|,|\n|" | grep -v "^hicolor$")
	inherits=$(echo -e "$icontheme\n$inherits\nhicolor" | sed "/^$/d")
	sizes=$(find "$iconpath" -type d | sed -n "s|^"$iconpath"/\([^/]*/\)\{0,1\}\([0-9]*\)[^/]*$|\2|p" | sort -u | awk -v iconsize="$iconsize" '{if($0 > iconsize) print "g "$0}{if($0 == iconsize) print "e "$0}{if ($0 < iconsize) print "l "$0}')
	sizes=$(echo -e "$(echo "$sizes" | grep "^e.*")\n$(echo "$sizes" | grep "^g.*" | sort -k 2.1n)\nscalable\n$(echo "$sizes" | grep "^l.*" | sort -k 2.1nr)")
	sizes=$(echo "$sizes" | sed "s|^. ||")
	icon=""
	for theme in $inherits; do
		themepath="/usr/share/icons/$theme"
		for size in $sizes; do
			for path in $(find $themepath -type d | grep "^$themepath/\([^/]*/\)\?$size\(x$size\)\?$"); do
				echo $path
				if $cansvg; then
					icon=$(find "$path" -type f -name "$iconname.png" -o -name "$iconname.svg")
				else
					icon=$(find "$path" -type f -name "$iconname.png")
				fi
				break
			done
			if ! [ -z "$icon" ]; then
				break
			fi
		done
		if ! [ -z "$icon" ]; then
			break
		fi
	done
	echo $icon
fi
# This line finds all paths given a theme and a size
# find $iconpath -type d | grep "^$iconpath/\([^/]*/\)\?$iconsize\(x$iconsize\)\?$"