#!/bin/bash

OLDMAJOR=$(cat xlunch.c | grep 'int VERSION_MAJOR' | sed -r 's/.*= *|;.*//g')
OLDMINOR=$(cat xlunch.c | grep 'int VERSION_MINOR' | sed -r 's/.*= *|;.*//g')
OLDPATCH=$(cat xlunch.c | grep 'int VERSION_PATCH' | sed -r 's/.*= *|;.*//g')

echo -ne "New MAJOR VERSION ($OLDMAJOR): "
read MAJOR
if [ "$MAJOR" = "" ]; then MAJOR=$OLDMAJOR; fi

echo -ne "New MINOR VERSION ($OLDMINOR): "
read MINOR
if [ "$MINOR" = "" ]; then MINOR=$OLDMINOR; fi

echo -ne "New PATCH VERSION ($OLDPATCH): "
read PATCH
if [ "$PATCH" = "" ]; then PATCH=$OLDPATCH; fi


sed -r -i "s/(int VERSION_MAJOR *= *)[0-9]+/\\1$MAJOR/" xlunch.c
sed -r -i "s/(int VERSION_MINOR *= *)[0-9]+/\\1$MINOR/" xlunch.c
sed -r -i "s/(int VERSION_PATCH *= *)[0-9]+/\\1$PATCH/" xlunch.c

sed -r -i "s:v[0-9]+.[0-9]+.[0-9]+:v$MAJOR.$MINOR.$PATCH:g" docs/index.html

git commit -a -m "version update v$MAJOR.$MINOR.$PATCH"
git tag v$MAJOR.$MINOR.$PATCH
git push
git push --tags
